num = int (input ("Enter The Number :"))
match num:
    case 1:
        print(f"January :{num}")
    case 2:
        print(f"February :{num}")
    case 3:
        print(f"March :{num}")
    case 4:
        print(f"April :{num}")
    case 5:
        print(f"May :{num}")
    case 6:
        print(f"June :{num}")
    case 7:
        print(f"July :{num}")
    case 8:
        print(f"August :{num}")
    case 9:
        print(f"September :{num}")
    case 10:
        print(f"Octomber :{num}")
    case 11:
        print(f"November :{num}")
    case 12:
        print(f"December :{num}")
    case _:
        print("Invalid Number :")
