#✅LOGICAL ALL OPERATOR 
print("\n#1.AND operator")
a = 10
b = 20

print(a > 5 and b > 15)  #True (Dono Condition Sahi hai)
print(a > 15 and b > 15) #False (Ek Condition galat hai)

print("\n2.OR operator")
x = 10
y = 20

print(a > 5 or b > 25)  #True (Pehli Condition Sahi Hai)
print(a > 15 or b > 25) #False (Dono Galat Hai)

print("\n#3.NOT operator")
p = 10

print(not(p > 5))  #False (a > 5 True Tha, Not Se Ulta Ho Gaya)
print(not(p > 15)) #True (a > 15 False Tha, Not Se True Hogaya)


'''number1 = int(input("Enter number 1 "))
number2 = int(input("Enter number 2 "))
ans = number1>100 and number1>number2
print(ans)
ans = number1>100 or number1>number2
print(f"with OR {ans}")
ans=not(number1>100)
'''