#PRINT 'N' TO 1 NUMBERS
# WHILE LOOP
num = int (input ("Enter The Number :")) 
i = 1

while num >= i:
    print(num)
    num-=1

#------------------------------------------------

print("\n")  
#FOR LOOP
num = int (input ("Enter The Number :"))
i = 1
for i in range (num,i,-1):
    print(i)

print("\n")

#-----------------------------------------------
num = int (input ("Enter The Value :"))
i = num
while num >= 1:
    print(num)
    num-=1