''''
✅PYTHON OPERATOR
1.ARITHMETIC    OPERATOR 🎯
2.LOGIC         OPERATOR 🎯
3.Assignment    OPERATOR 🎯
4.IDENTITY      OPERATOR 🎯
5.MEMBERSHIP    OPERATOR 🎯
6.RELATION      OPERATOR 🎯
'''
#✅ARITHMETIC ALL OPERATOR 

value1 = int (input("Enter The Value 1 :"))
value2 = int (input("Enter The Value 2 :"))

print("\nAddition")
#1.TRICK ONE---------------------------------------------------- 
print("Addition of",value1," and ",value2,"is",value1 + value2)

#2.TRICK TWO-------------------------------------------------------------
print("Addition of {} and {} is {}".format(value1,value2,value1 + value2))

#3.TRICK THREE-------------------------------------------------
print(f"Addition of {value1} and {value2} is {value1 + value2}")

print("\nSubtraction")

print("Subtraction of",value1, "and", value2, "is", value1 - value2)
print("Subtraction of {} and {} is {}".format(value1,value2,value1 - value2))
print(f"Subtraction of {value1} and {value2} is {value1 - value2}")

print("\nMultiplication")

print("Multiplication of",value1 ,"and", value2,"is",value1 * value2)
print("Multiplication of {} and {} is {}".format(value1,value2,value1 * value2))
print(f"Multiplication of {value1} and {value2} is {value1 * value2}")

print("\nDivision")
print("Division of",value1,"and",value2,"is",value1 / value2)
print("Division of {} and {} is {}".format(value1,value2,value1 / value2))
print(f"Division of {value1} and {value2} is {value1 / value2}")

print("\nModules")
print("Remainder of",value1,"and",value2,"is",value1 % value2)
print("Remainder of {} is {} and {}".format(value1,value2,value1 % value2))
print(f"Remainder of {value1} and {value2} is {value1 % value2}")


