#TYPE CONVERSION 
num1 = input ("Enter The Number =")

convert1 = int (num1)
convert2 = float(num1)
convert3 = float (num1)
convert4 = int (num1)
print("\nType Casting Is Integer Number =",convert1)
print("\nType Casting Is Floating point Number =",convert2)

print("\n===================================================")

print("\nType Casting Is Float Number =",convert3)
print("\nType Casting Is Integer Number =",convert4)

print("===================================================")
