for i in range (10):
    if i == 4:
        break
    print(i)


for j in range (10):
    if j == 4:
        print(j)
        break

i = 0
while i <= 10:
    print(i)
    if i ==4:
        break
    i+=1

for i in range (10):
    if i == 4:
        continue
    print(i)


for i in range (10):
    print(i)
    if i == 4:
        continue
    
for i in range (10):
    if i == 4:
        pass
    print(i)

for i in range (10):
    # if i == 4:
    #     pass
    print(i)

i = 0
while i <=10:
    pass
