#WHILE LOOP SIMPLE SEQUENCE
#PRINT INTO 1 TO 10 NUMBER
i = 1
while i <= 10:
    print(i)
    i+=1
'''
Dry Run 1 (i = 1 → 10)

Start: i = 1
Condition: i <= 10 (True)
Print 1 → i = i+1 = 2
Print 2 → i = 3
…
Print 9 → i = 10
Condition 11 < 11 (False) → loop stop
'''
print("\n")#---------------------------------------------------------------------
#WHILE LOOP REVERSE SEQUENCE
i = 10
while i >= 1:
    print(i)
    i-=1
print("\n")#---------------------------------------------------------------------


